//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Адрес.
    /// </summary>
    // *** Start programmer edit section *** (Адрес CustomAttributes)

    // *** End programmer edit section *** (Адрес CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АдресE", new string[] {
            "Город as \'Город\'"})]
    [View("АдресL", new string[] {
            "Город as \'Город\'"})]
    public class Адрес : ICSSoft.STORMNET.DataObject
    {
        
        private string fГород;
        
        // *** Start programmer edit section *** (Адрес CustomMembers)

        // *** End programmer edit section *** (Адрес CustomMembers)

        
        /// <summary>
        /// Город.
        /// </summary>
        // *** Start programmer edit section *** (Адрес.Город CustomAttributes)

        // *** End programmer edit section *** (Адрес.Город CustomAttributes)
        [StrLen(255)]
        public virtual string Город
        {
            get
            {
                // *** Start programmer edit section *** (Адрес.Город Get start)

                // *** End programmer edit section *** (Адрес.Город Get start)
                string result = this.fГород;
                // *** Start programmer edit section *** (Адрес.Город Get end)

                // *** End programmer edit section *** (Адрес.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Адрес.Город Set start)

                // *** End programmer edit section *** (Адрес.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (Адрес.Город Set end)

                // *** End programmer edit section *** (Адрес.Город Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АдресE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдресE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдресE", typeof(IIS.Kofeavtomat.Адрес));
                }
            }
            
            /// <summary>
            /// "АдресL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдресL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдресL", typeof(IIS.Kofeavtomat.Адрес));
                }
            }
        }
    }
}
