//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Допы.
    /// </summary>
    // *** Start programmer edit section *** (Допы CustomAttributes)

    // *** End programmer edit section *** (Допы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДопыE", new string[] {
            "Наименование as \'Наименование\'",
            "Количество as \'Количество\'",
            "Объем as \'Объем\'"})]
    public class Допы : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fКоличество;
        
        private IIS.Kofeavtomat.Объемы fОбъем;
        
        private IIS.Kofeavtomat.Кофе fКофе;
        
        // *** Start programmer edit section *** (Допы CustomMembers)

        // *** End programmer edit section *** (Допы CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Допы.Количество CustomAttributes)

        // *** End programmer edit section *** (Допы.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Допы.Количество Get start)

                // *** End programmer edit section *** (Допы.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Допы.Количество Get end)

                // *** End programmer edit section *** (Допы.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допы.Количество Set start)

                // *** End programmer edit section *** (Допы.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Допы.Количество Set end)

                // *** End programmer edit section *** (Допы.Количество Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Допы.Наименование CustomAttributes)

        // *** End programmer edit section *** (Допы.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Допы.Наименование Get start)

                // *** End programmer edit section *** (Допы.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Допы.Наименование Get end)

                // *** End programmer edit section *** (Допы.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допы.Наименование Set start)

                // *** End programmer edit section *** (Допы.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Допы.Наименование Set end)

                // *** End programmer edit section *** (Допы.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Объем.
        /// </summary>
        // *** Start programmer edit section *** (Допы.Объем CustomAttributes)

        // *** End programmer edit section *** (Допы.Объем CustomAttributes)
        public virtual IIS.Kofeavtomat.Объемы Объем
        {
            get
            {
                // *** Start programmer edit section *** (Допы.Объем Get start)

                // *** End programmer edit section *** (Допы.Объем Get start)
                IIS.Kofeavtomat.Объемы result = this.fОбъем;
                // *** Start programmer edit section *** (Допы.Объем Get end)

                // *** End programmer edit section *** (Допы.Объем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допы.Объем Set start)

                // *** End programmer edit section *** (Допы.Объем Set start)
                this.fОбъем = value;
                // *** Start programmer edit section *** (Допы.Объем Set end)

                // *** End programmer edit section *** (Допы.Объем Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kofeavtomat.Кофе.
        /// </summary>
        // *** Start programmer edit section *** (Допы.Кофе CustomAttributes)

        // *** End programmer edit section *** (Допы.Кофе CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Кофе"})]
        public virtual IIS.Kofeavtomat.Кофе Кофе
        {
            get
            {
                // *** Start programmer edit section *** (Допы.Кофе Get start)

                // *** End programmer edit section *** (Допы.Кофе Get start)
                IIS.Kofeavtomat.Кофе result = this.fКофе;
                // *** Start programmer edit section *** (Допы.Кофе Get end)

                // *** End programmer edit section *** (Допы.Кофе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допы.Кофе Set start)

                // *** End programmer edit section *** (Допы.Кофе Set start)
                this.fКофе = value;
                // *** Start programmer edit section *** (Допы.Кофе Set end)

                // *** End programmer edit section *** (Допы.Кофе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДопыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДопыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДопыE", typeof(IIS.Kofeavtomat.Допы));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Допы.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfДопы CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfДопы CustomAttributes)
    public class DetailArrayOfДопы : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kofeavtomat.DetailArrayOfДопы members)

        // *** End programmer edit section *** (IIS.Kofeavtomat.DetailArrayOfДопы members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Допы by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Допы.
        /// </summary>
        public DetailArrayOfДопы(IIS.Kofeavtomat.Кофе fКофе) : 
                base(typeof(Допы), ((ICSSoft.STORMNET.DataObject)(fКофе)))
        {
        }
        
        public IIS.Kofeavtomat.Допы this[int index]
        {
            get
            {
                return ((IIS.Kofeavtomat.Допы)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kofeavtomat.Допы dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
