//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "Номер as \'ID\'",
            "Телефон as \'Телефон\'"})]
    [View("КлиентL", new string[] {
            "Номер as \'ID\'",
            "Телефон as \'Телефон\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fТелефон;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Номер CustomAttributes)

        // *** End programmer edit section *** (Клиент.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Номер Get start)

                // *** End programmer edit section *** (Клиент.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Клиент.Номер Get end)

                // *** End programmer edit section *** (Клиент.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Номер Set start)

                // *** End programmer edit section *** (Клиент.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Клиент.Номер Set end)

                // *** End programmer edit section *** (Клиент.Номер Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Телефон CustomAttributes)

        // *** End programmer edit section *** (Клиент.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Телефон Get start)

                // *** End programmer edit section *** (Клиент.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Клиент.Телефон Get end)

                // *** End programmer edit section *** (Клиент.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Телефон Set start)

                // *** End programmer edit section *** (Клиент.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Клиент.Телефон Set end)

                // *** End programmer edit section *** (Клиент.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.Kofeavtomat.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.Kofeavtomat.Клиент));
                }
            }
        }
    }
}
