//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кофе машина.
    /// </summary>
    // *** Start programmer edit section *** (КофеМашина CustomAttributes)

    // *** End programmer edit section *** (КофеМашина CustomAttributes)
    [AutoAltered()]
    [Caption("Кофе машина")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КофеМашинаE", new string[] {
            "id as \'Id\'",
            "Состояние as \'Состояние\'",
            "Этаж.Здание.Адрес.Город as \'Город\'",
            "Этаж.Здание as \'Здание\'",
            "Этаж.Здание.Адреса as \'Адрес\'",
            "Этаж.Здание.НомерДома as \'НомерДома\'",
            "Этаж as \'Этаж\'",
            "Этаж.Этаж as \'Этаж\'",
            "Обслуживание as \'Обслуживание\'",
            "Обслуживание.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Этаж.Здание.Адрес.Город",
            "Этаж.Здание.НомерДома",
            "Этаж.Этаж",
            "Обслуживание.Наименование"})]
    [AssociatedDetailViewAttribute("КофеМашинаE", "СоставЗаказа", "СоставЗаказаE", true, "", "Состав заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("КофеМашинаE", "Этаж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Этаж")]
    [MasterViewDefineAttribute("КофеМашинаE", "Обслуживание", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("КофеМашинаL", new string[] {
            "id as \'Id\'",
            "Состояние as \'Состояние\'",
            "Этаж.Здание.Адрес.Город as \'Город\'",
            "Этаж.Здание.Адреса as \'Адрес\'",
            "Этаж.Здание.НомерДома as \'НомерДома\'",
            "Этаж.Этаж as \'Этаж\'",
            "Обслуживание.Наименование as \'Наименование\'"})]
    public class КофеМашина : ICSSoft.STORMNET.DataObject
    {
        
        private int fid;
        
        private IIS.Kofeavtomat.Состояния fСостояние;
        
        private IIS.Kofeavtomat.Этаж fЭтаж;
        
        private IIS.Kofeavtomat.Обслуживание fОбслуживание;
        
        private IIS.Kofeavtomat.DetailArrayOfСоставЗаказа fСоставЗаказа;
        
        // *** Start programmer edit section *** (КофеМашина CustomMembers)

        // *** End programmer edit section *** (КофеМашина CustomMembers)

        
        /// <summary>
        /// id.
        /// </summary>
        // *** Start programmer edit section *** (КофеМашина.id CustomAttributes)

        // *** End programmer edit section *** (КофеМашина.id CustomAttributes)
        public virtual int id
        {
            get
            {
                // *** Start programmer edit section *** (КофеМашина.id Get start)

                // *** End programmer edit section *** (КофеМашина.id Get start)
                int result = this.fid;
                // *** Start programmer edit section *** (КофеМашина.id Get end)

                // *** End programmer edit section *** (КофеМашина.id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КофеМашина.id Set start)

                // *** End programmer edit section *** (КофеМашина.id Set start)
                this.fid = value;
                // *** Start programmer edit section *** (КофеМашина.id Set end)

                // *** End programmer edit section *** (КофеМашина.id Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (КофеМашина.Состояние CustomAttributes)

        // *** End programmer edit section *** (КофеМашина.Состояние CustomAttributes)
        public virtual IIS.Kofeavtomat.Состояния Состояние
        {
            get
            {
                // *** Start programmer edit section *** (КофеМашина.Состояние Get start)

                // *** End programmer edit section *** (КофеМашина.Состояние Get start)
                IIS.Kofeavtomat.Состояния result = this.fСостояние;
                // *** Start programmer edit section *** (КофеМашина.Состояние Get end)

                // *** End programmer edit section *** (КофеМашина.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КофеМашина.Состояние Set start)

                // *** End programmer edit section *** (КофеМашина.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (КофеМашина.Состояние Set end)

                // *** End programmer edit section *** (КофеМашина.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Кофе машина.
        /// </summary>
        // *** Start programmer edit section *** (КофеМашина.Обслуживание CustomAttributes)

        // *** End programmer edit section *** (КофеМашина.Обслуживание CustomAttributes)
        [PropertyStorage(new string[] {
                "Обслуживание"})]
        [NotNull()]
        public virtual IIS.Kofeavtomat.Обслуживание Обслуживание
        {
            get
            {
                // *** Start programmer edit section *** (КофеМашина.Обслуживание Get start)

                // *** End programmer edit section *** (КофеМашина.Обслуживание Get start)
                IIS.Kofeavtomat.Обслуживание result = this.fОбслуживание;
                // *** Start programmer edit section *** (КофеМашина.Обслуживание Get end)

                // *** End programmer edit section *** (КофеМашина.Обслуживание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КофеМашина.Обслуживание Set start)

                // *** End programmer edit section *** (КофеМашина.Обслуживание Set start)
                this.fОбслуживание = value;
                // *** Start programmer edit section *** (КофеМашина.Обслуживание Set end)

                // *** End programmer edit section *** (КофеМашина.Обслуживание Set end)
            }
        }
        
        /// <summary>
        /// Кофе машина.
        /// </summary>
        // *** Start programmer edit section *** (КофеМашина.Этаж CustomAttributes)

        // *** End programmer edit section *** (КофеМашина.Этаж CustomAttributes)
        [PropertyStorage(new string[] {
                "Этаж"})]
        [NotNull()]
        public virtual IIS.Kofeavtomat.Этаж Этаж
        {
            get
            {
                // *** Start programmer edit section *** (КофеМашина.Этаж Get start)

                // *** End programmer edit section *** (КофеМашина.Этаж Get start)
                IIS.Kofeavtomat.Этаж result = this.fЭтаж;
                // *** Start programmer edit section *** (КофеМашина.Этаж Get end)

                // *** End programmer edit section *** (КофеМашина.Этаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КофеМашина.Этаж Set start)

                // *** End programmer edit section *** (КофеМашина.Этаж Set start)
                this.fЭтаж = value;
                // *** Start programmer edit section *** (КофеМашина.Этаж Set end)

                // *** End programmer edit section *** (КофеМашина.Этаж Set end)
            }
        }
        
        /// <summary>
        /// Кофе машина.
        /// </summary>
        // *** Start programmer edit section *** (КофеМашина.СоставЗаказа CustomAttributes)

        // *** End programmer edit section *** (КофеМашина.СоставЗаказа CustomAttributes)
        public virtual IIS.Kofeavtomat.DetailArrayOfСоставЗаказа СоставЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (КофеМашина.СоставЗаказа Get start)

                // *** End programmer edit section *** (КофеМашина.СоставЗаказа Get start)
                if ((this.fСоставЗаказа == null))
                {
                    this.fСоставЗаказа = new IIS.Kofeavtomat.DetailArrayOfСоставЗаказа(this);
                }
                IIS.Kofeavtomat.DetailArrayOfСоставЗаказа result = this.fСоставЗаказа;
                // *** Start programmer edit section *** (КофеМашина.СоставЗаказа Get end)

                // *** End programmer edit section *** (КофеМашина.СоставЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КофеМашина.СоставЗаказа Set start)

                // *** End programmer edit section *** (КофеМашина.СоставЗаказа Set start)
                this.fСоставЗаказа = value;
                // *** Start programmer edit section *** (КофеМашина.СоставЗаказа Set end)

                // *** End programmer edit section *** (КофеМашина.СоставЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КофеМашинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КофеМашинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КофеМашинаE", typeof(IIS.Kofeavtomat.КофеМашина));
                }
            }
            
            /// <summary>
            /// "КофеМашинаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КофеМашинаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КофеМашинаL", typeof(IIS.Kofeavtomat.КофеМашина));
                }
            }
        }
    }
}
