//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Материалы.
    /// </summary>
    // *** Start programmer edit section *** (Материалы CustomAttributes)

    // *** End programmer edit section *** (Материалы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МатериалыE", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Материалы : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.Kofeavtomat.Кофе fКофе;
        
        // *** Start programmer edit section *** (Материалы CustomMembers)

        // *** End programmer edit section *** (Материалы CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Материалы.Наименование CustomAttributes)

        // *** End programmer edit section *** (Материалы.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Материалы.Наименование Get start)

                // *** End programmer edit section *** (Материалы.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Материалы.Наименование Get end)

                // *** End programmer edit section *** (Материалы.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материалы.Наименование Set start)

                // *** End programmer edit section *** (Материалы.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Материалы.Наименование Set end)

                // *** End programmer edit section *** (Материалы.Наименование Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kofeavtomat.Кофе.
        /// </summary>
        // *** Start programmer edit section *** (Материалы.Кофе CustomAttributes)

        // *** End programmer edit section *** (Материалы.Кофе CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Кофе"})]
        public virtual IIS.Kofeavtomat.Кофе Кофе
        {
            get
            {
                // *** Start programmer edit section *** (Материалы.Кофе Get start)

                // *** End programmer edit section *** (Материалы.Кофе Get start)
                IIS.Kofeavtomat.Кофе result = this.fКофе;
                // *** Start programmer edit section *** (Материалы.Кофе Get end)

                // *** End programmer edit section *** (Материалы.Кофе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материалы.Кофе Set start)

                // *** End programmer edit section *** (Материалы.Кофе Set start)
                this.fКофе = value;
                // *** Start programmer edit section *** (Материалы.Кофе Set end)

                // *** End programmer edit section *** (Материалы.Кофе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МатериалыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалыE", typeof(IIS.Kofeavtomat.Материалы));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Материалы.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfМатериалы CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfМатериалы CustomAttributes)
    public class DetailArrayOfМатериалы : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kofeavtomat.DetailArrayOfМатериалы members)

        // *** End programmer edit section *** (IIS.Kofeavtomat.DetailArrayOfМатериалы members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Материалы by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Материалы.
        /// </summary>
        public DetailArrayOfМатериалы(IIS.Kofeavtomat.Кофе fКофе) : 
                base(typeof(Материалы), ((ICSSoft.STORMNET.DataObject)(fКофе)))
        {
        }
        
        public IIS.Kofeavtomat.Материалы this[int index]
        {
            get
            {
                return ((IIS.Kofeavtomat.Материалы)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kofeavtomat.Материалы dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
