//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Объемы.
    /// </summary>
    // *** Start programmer edit section *** (Объемы CustomAttributes)

    // *** End programmer edit section *** (Объемы CustomAttributes)
    public enum Объемы
    {
        
        // *** Start programmer edit section *** (Объемы.Гр CustomAttributes)

        // *** End programmer edit section *** (Объемы.Гр CustomAttributes)
        [Caption("Гр")]
        Гр,
        
        // *** Start programmer edit section *** (Объемы.Кг CustomAttributes)

        // *** End programmer edit section *** (Объемы.Кг CustomAttributes)
        [Caption("Кг")]
        Кг,
        
        // *** Start programmer edit section *** (Объемы.Л CustomAttributes)

        // *** End programmer edit section *** (Объемы.Л CustomAttributes)
        [Caption("Л")]
        Л,
        
        // *** Start programmer edit section *** (Объемы.Мл CustomAttributes)

        // *** End programmer edit section *** (Объемы.Мл CustomAttributes)
        [Caption("Мл")]
        Мл,
    }
}
