//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обслуживание.
    /// </summary>
    // *** Start programmer edit section *** (Обслуживание CustomAttributes)

    // *** End programmer edit section *** (Обслуживание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбслуживаниеE", new string[] {
            "Наименование as \'Наименование\'",
            "Этаж as \'Этаж\'",
            "Этаж.Этаж as \'Этаж\'"}, Hidden=new string[] {
            "Этаж.Этаж"})]
    [MasterViewDefineAttribute("ОбслуживаниеE", "Этаж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Этаж")]
    [View("ОбслуживаниеL", new string[] {
            "Наименование as \'Наименование\'",
            "Этаж.Этаж as \'Этаж\'"})]
    public class Обслуживание : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.Kofeavtomat.Этаж fЭтаж;
        
        // *** Start programmer edit section *** (Обслуживание CustomMembers)

        // *** End programmer edit section *** (Обслуживание CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.Наименование CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.Наименование Get start)

                // *** End programmer edit section *** (Обслуживание.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Обслуживание.Наименование Get end)

                // *** End programmer edit section *** (Обслуживание.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.Наименование Set start)

                // *** End programmer edit section *** (Обслуживание.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Обслуживание.Наименование Set end)

                // *** End programmer edit section *** (Обслуживание.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Обслуживание.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.Этаж CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.Этаж CustomAttributes)
        [PropertyStorage(new string[] {
                "Этаж"})]
        [NotNull()]
        public virtual IIS.Kofeavtomat.Этаж Этаж
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.Этаж Get start)

                // *** End programmer edit section *** (Обслуживание.Этаж Get start)
                IIS.Kofeavtomat.Этаж result = this.fЭтаж;
                // *** Start programmer edit section *** (Обслуживание.Этаж Get end)

                // *** End programmer edit section *** (Обслуживание.Этаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.Этаж Set start)

                // *** End programmer edit section *** (Обслуживание.Этаж Set start)
                this.fЭтаж = value;
                // *** Start programmer edit section *** (Обслуживание.Этаж Set end)

                // *** End programmer edit section *** (Обслуживание.Этаж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбслуживаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбслуживаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбслуживаниеE", typeof(IIS.Kofeavtomat.Обслуживание));
                }
            }
            
            /// <summary>
            /// "ОбслуживаниеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбслуживаниеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбслуживаниеL", typeof(IIS.Kofeavtomat.Обслуживание));
                }
            }
        }
    }
}
