//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплаты.
    /// </summary>
    // *** Start programmer edit section *** (Оплаты CustomAttributes)

    // *** End programmer edit section *** (Оплаты CustomAttributes)
    public enum Оплаты
    {
        
        // *** Start programmer edit section *** (Оплаты.Крипта CustomAttributes)

        // *** End programmer edit section *** (Оплаты.Крипта CustomAttributes)
        [Caption("Крипта")]
        Крипта,
        
        // *** Start programmer edit section *** (Оплаты.Безнал CustomAttributes)

        // *** End programmer edit section *** (Оплаты.Безнал CustomAttributes)
        [Caption("Безнал")]
        Безнал,
        
        // *** Start programmer edit section *** (Оплаты.Нал CustomAttributes)

        // *** End programmer edit section *** (Оплаты.Нал CustomAttributes)
        [Caption("Нал")]
        Нал,
        
        // *** Start programmer edit section *** (Оплаты.Q CustomAttributes)

        // *** End programmer edit section *** (Оплаты.Q CustomAttributes)
        Q,
        
        // *** Start programmer edit section *** (Оплаты.код CustomAttributes)

        // *** End programmer edit section *** (Оплаты.код CustomAttributes)
        код,
    }
}
