//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав заказа.
    /// </summary>
    // *** Start programmer edit section *** (СоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (СоставЗаказа CustomAttributes)
    [AutoAltered()]
    [Caption("Состав заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставЗаказаE", new string[] {
            "Сумма as \'Сумма\'",
            "Заказ as \'Заказ\'",
            "Заказ.Id as \'Id\'",
            "Заказ.Клиент as \'Клиент\'",
            "Заказ.Клиент.id as \'ID клиента\'",
            "Заказ.Оплата as \'Оплата\'",
            "Заказ.Оплата.ТипОплаты as \'Тип оплаты\'"}, Hidden=new string[] {
            "Заказ.Id"})]
    [MasterViewDefineAttribute("СоставЗаказаE", "Заказ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Id")]
    public class СоставЗаказа : ICSSoft.STORMNET.DataObject
    {
        
        private double fСумма;
        
        private IIS.Kofeavtomat.Заказ fЗаказ;
        
        private IIS.Kofeavtomat.КофеМашина fКофеМашина;
        
        // *** Start programmer edit section *** (СоставЗаказа CustomMembers)

        // *** End programmer edit section *** (СоставЗаказа CustomMembers)

        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Сумма CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Сумма Get start)

                // *** End programmer edit section *** (СоставЗаказа.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (СоставЗаказа.Сумма Get end)

                // *** End programmer edit section *** (СоставЗаказа.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Сумма Set start)

                // *** End programmer edit section *** (СоставЗаказа.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (СоставЗаказа.Сумма Set end)

                // *** End programmer edit section *** (СоставЗаказа.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Состав заказа.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Заказ CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Заказ CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказ"})]
        [NotNull()]
        public virtual IIS.Kofeavtomat.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Get start)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Get start)
                IIS.Kofeavtomat.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Get end)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Set start)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Set end)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kofeavtomat.КофеМашина.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.КофеМашина CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.КофеМашина CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "КофеМашина"})]
        public virtual IIS.Kofeavtomat.КофеМашина КофеМашина
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.КофеМашина Get start)

                // *** End programmer edit section *** (СоставЗаказа.КофеМашина Get start)
                IIS.Kofeavtomat.КофеМашина result = this.fКофеМашина;
                // *** Start programmer edit section *** (СоставЗаказа.КофеМашина Get end)

                // *** End programmer edit section *** (СоставЗаказа.КофеМашина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.КофеМашина Set start)

                // *** End programmer edit section *** (СоставЗаказа.КофеМашина Set start)
                this.fКофеМашина = value;
                // *** Start programmer edit section *** (СоставЗаказа.КофеМашина Set end)

                // *** End programmer edit section *** (СоставЗаказа.КофеМашина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставЗаказаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставЗаказаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставЗаказаE", typeof(IIS.Kofeavtomat.СоставЗаказа));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставЗаказа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)
    public class DetailArrayOfСоставЗаказа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kofeavtomat.DetailArrayOfСоставЗаказа members)

        // *** End programmer edit section *** (IIS.Kofeavtomat.DetailArrayOfСоставЗаказа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставЗаказа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставЗаказа.
        /// </summary>
        public DetailArrayOfСоставЗаказа(IIS.Kofeavtomat.КофеМашина fКофеМашина) : 
                base(typeof(СоставЗаказа), ((ICSSoft.STORMNET.DataObject)(fКофеМашина)))
        {
        }
        
        public IIS.Kofeavtomat.СоставЗаказа this[int index]
        {
            get
            {
                return ((IIS.Kofeavtomat.СоставЗаказа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kofeavtomat.СоставЗаказа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
