//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояния.
    /// </summary>
    // *** Start programmer edit section *** (Состояния CustomAttributes)

    // *** End programmer edit section *** (Состояния CustomAttributes)
    public enum Состояния
    {
        
        // *** Start programmer edit section *** (Состояния.Исправен CustomAttributes)

        // *** End programmer edit section *** (Состояния.Исправен CustomAttributes)
        [Caption("Исправен")]
        Исправен,
        
        // *** Start programmer edit section *** (Состояния.Неисправен CustomAttributes)

        // *** End programmer edit section *** (Состояния.Неисправен CustomAttributes)
        [Caption("Неисправен")]
        Неисправен,
    }
}
