//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kofeavtomat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стаканчик.
    /// </summary>
    // *** Start programmer edit section *** (Стаканчик CustomAttributes)

    // *** End programmer edit section *** (Стаканчик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтаканчикE", new string[] {
            "Номер as \'Номер\'",
            "Объем as \'Объем\'"})]
    public class Стаканчик : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fОбъем;
        
        private IIS.Kofeavtomat.Кофе fКофе;
        
        // *** Start programmer edit section *** (Стаканчик CustomMembers)

        // *** End programmer edit section *** (Стаканчик CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Стаканчик.Номер CustomAttributes)

        // *** End programmer edit section *** (Стаканчик.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Стаканчик.Номер Get start)

                // *** End programmer edit section *** (Стаканчик.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Стаканчик.Номер Get end)

                // *** End programmer edit section *** (Стаканчик.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стаканчик.Номер Set start)

                // *** End programmer edit section *** (Стаканчик.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Стаканчик.Номер Set end)

                // *** End programmer edit section *** (Стаканчик.Номер Set end)
            }
        }
        
        /// <summary>
        /// Объем.
        /// </summary>
        // *** Start programmer edit section *** (Стаканчик.Объем CustomAttributes)

        // *** End programmer edit section *** (Стаканчик.Объем CustomAttributes)
        public virtual int Объем
        {
            get
            {
                // *** Start programmer edit section *** (Стаканчик.Объем Get start)

                // *** End programmer edit section *** (Стаканчик.Объем Get start)
                int result = this.fОбъем;
                // *** Start programmer edit section *** (Стаканчик.Объем Get end)

                // *** End programmer edit section *** (Стаканчик.Объем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стаканчик.Объем Set start)

                // *** End programmer edit section *** (Стаканчик.Объем Set start)
                this.fОбъем = value;
                // *** Start programmer edit section *** (Стаканчик.Объем Set end)

                // *** End programmer edit section *** (Стаканчик.Объем Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kofeavtomat.Кофе.
        /// </summary>
        // *** Start programmer edit section *** (Стаканчик.Кофе CustomAttributes)

        // *** End programmer edit section *** (Стаканчик.Кофе CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Кофе"})]
        public virtual IIS.Kofeavtomat.Кофе Кофе
        {
            get
            {
                // *** Start programmer edit section *** (Стаканчик.Кофе Get start)

                // *** End programmer edit section *** (Стаканчик.Кофе Get start)
                IIS.Kofeavtomat.Кофе result = this.fКофе;
                // *** Start programmer edit section *** (Стаканчик.Кофе Get end)

                // *** End programmer edit section *** (Стаканчик.Кофе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стаканчик.Кофе Set start)

                // *** End programmer edit section *** (Стаканчик.Кофе Set start)
                this.fКофе = value;
                // *** Start programmer edit section *** (Стаканчик.Кофе Set end)

                // *** End programmer edit section *** (Стаканчик.Кофе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтаканчикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтаканчикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтаканчикE", typeof(IIS.Kofeavtomat.Стаканчик));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Стаканчик.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтаканчик CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтаканчик CustomAttributes)
    public class DetailArrayOfСтаканчик : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kofeavtomat.DetailArrayOfСтаканчик members)

        // *** End programmer edit section *** (IIS.Kofeavtomat.DetailArrayOfСтаканчик members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Стаканчик by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Стаканчик.
        /// </summary>
        public DetailArrayOfСтаканчик(IIS.Kofeavtomat.Кофе fКофе) : 
                base(typeof(Стаканчик), ((ICSSoft.STORMNET.DataObject)(fКофе)))
        {
        }
        
        public IIS.Kofeavtomat.Стаканчик this[int index]
        {
            get
            {
                return ((IIS.Kofeavtomat.Стаканчик)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kofeavtomat.Стаканчик dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
